# Hugo MCP Server — environment configuration
# Generated by mcp-installer

# === Required ===
MCP_TOKEN=__TOKEN__
HUGO_SITE_DIR=__HUGO_SITE__
BASE_URL=__BASE_URL__

# === Deploy script ===
DEPLOY_SH=__DEPLOY_SH__

# === Optional: Cloudflare cache purge (leave empty to disable) ===
CF_TOKEN=__CF_TOKEN__
CF_ZONE_ID=__CF_ZONE_ID__

# === Optional: Phase 4 SEO features (OFF by default) ===
SEO_PINGS_ENABLED=false
SEO_PUBLIC_HOST=
INDEXNOW_KEY=

# === Optional: Phase 3 LLM auto-SEO (OFF by default) ===
ANTHROPIC_API_KEY=

# === Logging ===
HUGO_MCP_LOG_LEVEL=INFO
