# MCP OAuth Proxy — environment configuration
# Generated by mcp-installer
# Permissions: chmod 600 — never commit this file

# OAuth 2.1 client credentials (register these in Claude.ai MCP connector)
CLIENT_ID=__CLIENT_ID__
CLIENT_SECRET=__CLIENT_SECRET__

# Backend MCP token (must match MCP_TOKEN of the Hugo/Grav MCP backend)
GRAV_TOKEN=__BACKEND_TOKEN__

# Internal URL of the backend MCP endpoint
GRAV_MCP_URL=__BACKEND_URL__

# Backend host header (used for internal requests bypassing reverse proxy)
GRAV_HOST=__BACKEND_HOST__

# Public base URL of this proxy (used in OAuth discovery endpoints)
PROXY_BASE_URL=https://__DOMAIN__

# Token storage (SHA-256 hashes only, never plain tokens)
TOKENS_FILE=/opt/mcp-oauth-proxy/tokens.json

# Audit log file (JSON lines)
AUDIT_LOG_FILE=/var/log/mcp-oauth/audit.log

# Proxy listen address and port
LISTEN_HOST=127.0.0.1
LISTEN_PORT=__PORT__
